#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=CheckEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:05:00
#SBATCH --output=./output/slurm_output_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

# Activate your environment
source activate abm
# Check whether the GPU is available
srun python -uc "import torch; print('GPU available?', torch.cuda.is_available())"